ALTER TABLE [dbo].[Messages] ALTER COLUMN [EditIp] VARCHAR(39) NULL;
ALTER TABLE [dbo].[Topics] ALTER COLUMN [TopicLastEditIp] VARCHAR(39) NOT NULL;
ALTER TABLE [dbo].[Flags] ALTER COLUMN [Ip] VARCHAR(39) NOT NULL;